FROM n8nio/n8n:latest

USER root

ENV N8N_PORT=10000
ENV N8N_HOST=0.0.0.0
ENV N8N_PROTOCOL=https
ENV GENERIC_TIMEZONE=Africa/Abidjan
ENV N8N_DIAGNOSTICS_ENABLED=false
ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_HOST=dpg-d6lv3e1aae7s73f86eng-a.frankfurt-postgres.render.com
ENV DB_POSTGRESDB_PORT=5432
ENV DB_POSTGRESDB_DATABASE=n8n_database_qx49
ENV DB_POSTGRESDB_USER=n8n_database_qx49_user
ENV DB_POSTGRESDB_PASSWORD=Pez0OFlAlDYscCDAC6hq5bEt94oLfIyt
ENV DB_POSTGRESDB_SCHEMA=public
ENV DB_POSTGRESDB_SSL_ENABLED=true
ENV DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED=false

EXPOSE 10000

ENTRYPOINT ["tini", "--", "/docker-entrypoint.sh"]
